---
  - name: virtualbox | main.yml >> virtualbox dependencies present
    apt: package={{ item }} state=present
    with_items:
      - "linux-headers-{{ kernel }}"
      - dkms
      - build-essential
    tags: virtualbox

  - name: virtualbox | main.yml >> download virtualbox guest additions iso
    get_url: url={{ virtualbox.guest_additions.iso_url }} dest={{ virtualbox.guest_additions.iso_dir }}
    tags: virtualbox

  - name: virtualbox | main.yml >> ensure mount dir exists
    file: path={{ virtualbox.guest_additions.iso_mountdir }}/VBoxGuestAdditions_{{ virtualbox.guest_additions.version }} state=directory
    tags: virtualbox

  - name: virtualbox | main.yml >> mount virtualbox guest additions iso
    mount: name={{ virtualbox.guest_additions.iso_mountdir }} src={{ virtualbox.guest_additions.iso_dir }}/VBoxGuestAdditions_{{ virtualbox.guest_additions.version }}.iso fstype=iso9660 opts=ro state=present
    register: virtualbox_guest_additions_mounted
    tags: virtualbox

  - name: virtualbox | main.yml >> virtualbox guest additions present
    shell: sh {{ virtualbox.guest_additions.iso_mountdir }}/VBoxLinuxAdditions.run
    ignore_errors: true
    tags: virtualbox

  - name: virtualbox | main.yml >> umount virtualbox guest additions iso
    mount: name={{ virtualbox.guest_additions.iso_mountdir }} state=unmount
    when: virtualbox_guest_additions_mounted.changed
    tags: virtualbox