---
- name: PHP | Install PHP and Dependencies
  apt: pkg={{ item }} state=present
  with_items:
    - php7.0-fpm
    - php7.0-mysql
    - php7.0-dev
    - php7.0-json
    - php7.0-intl
    - php7.0-mcrypt
    - php7.0-curl
    - php7.0-cli
    - php7.0-xdebug
    - php7.0-memcached
    - php7.0-mbstring
    - php7.0-zip

- name: PHP | Install Composer
  get_url: url=https://getcomposer.org/composer.phar dest=/usr/local/bin/composer mode=0755 validate_certs=no

- name: PHP | Copy pool configuration
  template: src=www.conf dest=/etc/php/7.0/fpm/pool.d/
  notify: restart php7.0-fpm

- name: PHP | Restart PHP Server
  service: name=php7.0-fpm state=started enabled=true
