---
- name: Devious - An awesome LEMP stack Ansible for Software Engineers
  hosts: development
  user: vagrant
  become: true

  roles:
    # - vbox_guest_additions    # on enable vbox_guest_additions if required
    - system
    - git
    - nodejs                    # tasks includes grunt-cli and bower
    - ruby                      # tasks includes sass
    - mysql
    - php                       # tasks includes composer
    - memcached
    - nginx
